CREATE TABLE accomodation (
  latitude DECIMAL(10,8) NOT NULL,
  longitude DECIMAL(11,8) NOT NULL,
  id VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  advertiser VARCHAR(255) NOT NULL,
  ad_description TEXT,
  reformed BOOLEAN,
  phone_number VARCHAR(255),
  accomodation_type VARCHAR(255) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  price_per_meter DECIMAL(10,2),
  address VARCHAR(255),
  province VARCHAR(255),
  city VARCHAR(255),
  s_meters INT,
  rooms INT,
  bathrooms INT,
  parking BOOLEAN,
  second_hand BOOLEAN,
  fitted_wardrobes BOOLEAN,
  built_in INT,
  furnished BOOLEAN,
  heating BOOLEAN,
  e_certification VARCHAR(255),
  floor VARCHAR(255),
  exterior BOOLEAN,
  indoor BOOLEAN,
  elevator BOOLEAN,
  ad_date DATE,
  street VARCHAR(255),
  neighborhood VARCHAR(255),
  district VARCHAR(255),
  terrace BOOLEAN,
  storage_room BOOLEAN,
  kitchen BOOLEAN,
  equipped_kitchen BOOLEAN,
  air_conditioning BOOLEAN,
  pool BOOLEAN,
  garden BOOLEAN,
  useful_s_meters INT,
  reduced_mobility_friendly BOOLEAN,
  floors INT,
  pet_friendly BOOLEAN,
  balcony BOOLEAN
);

CREATE TABLE users (
email VARCHAR(25) NOT NULL,
pass VARCHAR(25) NOT NULL
);
